apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraudguard-ingress
  namespace: fraudguard
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "fraudguard-ip"
    networking.gke.io/managed-certificates: "fraudguard-ssl-cert"
    kubernetes.io/ingress.allow-http: "true"
spec:
  tls:
  - hosts:
    - fraudguard.mohankrishna.site
    secretName: fraudguard-ssl-cert
  rules:
  - host: fraudguard.mohankrishna.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard
            port:
              number: 8080
      - path: /api/mcp
        pathType: Prefix
        backend:
          service:
            name: mcp-gateway
            port:
              number: 8080
      - path: /api/risk
        pathType: Prefix
        backend:
          service:
            name: risk-scorer
            port:
              number: 8080
      - path: /api/explain
        pathType: Prefix
        backend:
          service:
            name: explain-agent
            port:
              number: 8080
      - path: /api/action
        pathType: Prefix
        backend:
          service:
            name: action-orchestrator
            port:
              number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: fraudguard-ssl-cert
  namespace: fraudguard
spec:
  domains:
    - fraudguard.mohankrishna.site
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: fraudguard
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: fraudguard
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mcp-gateway
