{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "workload.fullname" . }}-secrets
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  provider: gcp
  {{- if .Values.secretManager.secretProviderClass }}
  {{- toYaml .Values.secretManager.secretProviderClass.spec | nindent 2 }}
  {{- else }}
  # Default configuration - override in values files
  parameters:
    secrets: |
      - resourceName: "projects/PROJECT_ID/secrets/example-secret/versions/latest"
        path: "example-secret"
  {{- end }}
{{- end }}
